# coding=utf-8
from docx import Document
from docx.shared import Pt


datos=[{"departamento":"Cajamarca","Nro":1,"PROCEDIMIENTO":"DESLINDE Y TITULACION CC.CC","personal":"ABOGADO DE CAMPO 1","orden":1,"provincia":"Contumaza","utm1":"San Benito","utm2":"San Benito","utm3":"San Benito","seccion":"Sección 1","area":"Área 1","GRUPO":"DESLINDE - PERSONAL CAMPO","tipopredio":"CC.CC","codigopersonal":"P66-CAJ-CC-CAMP-ABG-DE-CAMPO","objeto":"en materia legal para verificar y evaluar documentación legal obtenida en campo y control de calidad del deslinde y titulación de CC.CC"},
{"departamento":"Cajamarca","Nro":2,"PROCEDIMIENTO":"DESLINDE Y TITULACION CC.CC","personal":"ABOGADO DE CAMPO 2","orden":2,"provincia":"San Marcos","utm1":"Socchagon","utm2":"Socchagon","utm3":"Socchagon","seccion":"Sección 2","area":"Área 2","GRUPO":"DESLINDE - PERSONAL CAMPO","tipopredio":"CC.CC","codigopersonal":"P66-CAJ-CC-CAMP-ABG-DE-CAMPO","objeto":"en materia legal para verificar y evaluar documentación legal obtenida en campo y control de calidad del deslinde y titulación de CC.CC"},
{"departamento":"Cajamarca","Nro":3,"PROCEDIMIENTO":"DESLINDE Y TITULACION CC.CC","personal":"ABOGADO DE CAMPO 3","orden":3,"provincia":"San Marcos, Cajamarca","utm1":"Pomarongo Shillabamba, Cushunga","utm2":"Pomarongo Shillabamba, Cushunga","utm3":"Pomarongo Shillabamba, Cushunga","seccion":"Sección 3","area":"Área 3","GRUPO":"DESLINDE - PERSONAL CAMPO","tipopredio":"CC.CC","codigopersonal":"P66-CAJ-CC-CAMP-ABG-DE-CAMPO","objeto":"en materia legal para verificar y evaluar documentación legal obtenida en campo y control de calidad del deslinde y titulación de CC.CC"},
{"departamento":"Cajamarca","Nro":11,"PROCEDIMIENTO":"DIAGNOSTICO CC.CC","personal":"ABOGADO DIAGNOSTICO 1","orden":1,"provincia":"Cajamarca","utm1":"Chirigpunta, Huacataz Laparpampa, Santa Maria Magdalena","utm2":"Chirigpunta, Huacataz Laparpampa, Santa Maria Magdalena","utm3":"Chirigpunta, Huacataz Laparpampa, Santa Maria Magdalena","seccion":"Sección 1","area":"Área 1","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"CC.CC","codigopersonal":"P73-CAJ-CC-DIAG-ABG-DIAG","objeto":"en materia legal para la elaboración de informes de diagnóstico fisico legal y socio ambiental de Comunidades Campesinas – CC.CC."},
{"departamento":"Cajamarca","Nro":12,"PROCEDIMIENTO":"DIAGNOSTICO CC.CC","personal":"ABOGADO DIAGNOSTICO 2","orden":2,"provincia":"Contumaza, San Miguel","utm1":"San Juan de Llallan, San Antonio de Ojos, Calquis","utm2":"San Juan de LLallan, San Antonio de Ojos, Calquis","utm3":"San Juan de LLallan, San Antonio de Ojos, Calquis","seccion":"Sección 2","area":"Área 2","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"CC.CC","codigopersonal":"P73-CAJ-CC-DIAG-ABG-DIAG","objeto":"en materia legal para la elaboración de informes de diagnóstico fisico legal y socio ambiental de Comunidades Campesinas – CC.CC."},
{"departamento":"Cajamarca","Nro":4,"PROCEDIMIENTO":"DESLINDE Y TITULACION CC.CC","personal":"ARQUEOLOGO 1","orden":1,"provincia":"Cajamarca, Contumaza, San Miguel","utm1":"Cajamarca, Contumaza, San Miguel, San Marcos","utm2":"Cajamarca, Contumaza, San Miguel, San Marcos","utm3":"Cajamarca, Contumaza, San Miguel, San Marcos","seccion":"","area":"","GRUPO":"DESLINDE - PERSONAL CAMPO","tipopredio":"CC.CC","codigopersonal":"P68-CAJ-CC-CAMP-ARQ","objeto":"para la identificacion de patrimonio cultural de la nación o zonas arqueologicas en campo"},
{"departamento":"Cajamarca","Nro":13,"PROCEDIMIENTO":"DIAGNOSTICO CC.CC","personal":"ESPECIALISTA CAD/GIS 1","orden":1,"provincia":"Cajamarca, contumaza, San Miguel","utm1":"Chirigpunta, Huacataz Laparpampa, Santa Maria Magdalena, San Juan de Llallan, San Antonio de Ojos, Calquis","utm2":"Chirigpunta, Huacataz Laparpampa, Santa Maria Magdalena, San Juan de LLallan, San Antonio de Ojos, Calquis","utm3":"Chirigpunta, Huacataz Laparpampa, Santa Maria Magdalena, San Juan de LLallan, San Antonio de Ojos, Calquis","seccion":"","area":"","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"CC.CC","codigopersonal":"P70-CAJ-CC-DIAG-ESP-CADGIS","objeto":"especializado en CAD / GIS para recopilar, procesar y analizar información de las bases gráficas con fines de diagnóstico físico legal de Comunidades Campesinas – CC.CC."},
{"departamento":"Cajamarca","Nro":14,"PROCEDIMIENTO":"DIAGNOSTICO CC.CC","personal":"INGENIERO DIAGNOSTICO 1","orden":1,"provincia":"Cajamarca","utm1":"Chirigpunta, Huacataz Laparpampa, Santa Maria Magdalena","utm2":"Chirigpunta, Huacataz Laparpampa, Santa Maria Magdalena","utm3":"Chirigpunta, Huacataz Laparpampa, Santa Maria Magdalena","seccion":"Sección 1","area":"Área 1","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"CC.CC","codigopersonal":"P72-CAJ-CC-DIAG-ING-DIAG","objeto":"materia técnica para la elaboración de informes de diagnóstico fisico legal y socio ambiental de Comunidades Campesinas – CC.CC."},
{"departamento":"Cajamarca","Nro":15,"PROCEDIMIENTO":"DIAGNOSTICO CC.CC","personal":"INGENIERO DIAGNOSTICO 2","orden":2,"provincia":"Contumaza, San Miguel","utm1":"San Juan de Llallan, San Antonio de Ojos, Calquis","utm2":"San Juan de LLallan, San Antonio de Ojos, Calquis","utm3":"San Juan de Llallan, San Antonio de Ojos, Calquis","seccion":"Sección 2","area":"Área 2","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"CC.CC","codigopersonal":"P72-CAJ-CC-DIAG-ING-DIAG","objeto":"materia técnica para la elaboración de informes de diagnóstico fisico legal y socio ambiental de Comunidades Campesinas – CC.CC."},
{"departamento":"Cajamarca","Nro":5,"PROCEDIMIENTO":"DESLINDE Y TITULACION CC.CC","personal":"INGENIERO EN CIENCIAS AGRARIAS (LIDER DE ETE) Y AMBIENTAL 1","orden":1,"provincia":"Contumaza","utm1":"San Benito","utm2":"San Benito","utm3":"San Benito","seccion":"Sección 1","area":"Área 1","GRUPO":"DESLINDE - PERSONAL CAMPO","tipopredio":"CC.CC","codigopersonal":"P65-CAJ-CC-CAMP-ING-EN-CS-AGR-LDR-DE-ETE-Y-AMB","objeto":"en materia técnica para coordinar, monitorear y efectuar el seguimiento al equipo técnico especializado en actividades de campo de Comunidades Campesinas – CC.CC."},
{"departamento":"Cajamarca","Nro":6,"PROCEDIMIENTO":"DESLINDE Y TITULACION CC.CC","personal":"INGENIERO EN CIENCIAS AGRARIAS (LIDER DE ETE) Y AMBIENTAL 2","orden":2,"provincia":"San Marcos","utm1":"Socchagon","utm2":"Socchagon","utm3":"Socchagon","seccion":"Sección 2","area":"Área 2","GRUPO":"DESLINDE - PERSONAL CAMPO","tipopredio":"CC.CC","codigopersonal":"P65-CAJ-CC-CAMP-ING-EN-CS-AGR-LDR-DE-ETE-Y-AMB","objeto":"en materia técnica para coordinar, monitorear y efectuar el seguimiento al equipo técnico especializado en actividades de campo de Comunidades Campesinas – CC.CC."},
{"departamento":"Cajamarca","Nro":7,"PROCEDIMIENTO":"DESLINDE Y TITULACION CC.CC","personal":"INGENIERO EN CIENCIAS AGRARIAS (LIDER DE ETE) Y AMBIENTAL 3","orden":3,"provincia":"San Marcos, Cajamarca","utm1":"Pomarongo Shillabamba, Cushunga","utm2":"Pomarongo Shillabamba, Cushunga","utm3":"Pomarongo Shillabamba, Cushunga","seccion":"Sección 3","area":"Área 3","GRUPO":"DESLINDE - PERSONAL CAMPO","tipopredio":"CC.CC","codigopersonal":"P65-CAJ-CC-CAMP-ING-EN-CS-AGR-LDR-DE-ETE-Y-AMB","objeto":"en materia técnica para coordinar, monitorear y efectuar el seguimiento al equipo técnico especializado en actividades de campo de Comunidades Campesinas – CC.CC."},
{"departamento":"Cajamarca","Nro":8,"PROCEDIMIENTO":"DESLINDE Y TITULACION CC.CC","personal":"TECNICO DE CAMPO 1","orden":1,"provincia":"Contumaza","utm1":"San Benito","utm2":"San Benito","utm3":"San Benito","seccion":"Sección 1","area":"Área 1","GRUPO":"DESLINDE - PERSONAL CAMPO","tipopredio":"CC.CC","codigopersonal":"P67-CAJ-PRI-CAMP-TEC-CAMPO","objeto":"en materia técnica para el deslinde y titulación de CC.CC."},
{"departamento":"Cajamarca","Nro":16,"PROCEDIMIENTO":"DIAGNOSTICO CC.CC","personal":"TECNICO DE CAMPO 1","orden":1,"provincia":"Cajamarca","utm1":"Chirigpunta, Huacataz Laparpampa, Santa Maria Magdalena","utm2":"Chirigpunta, Huacataz Laparpampa, Santa Maria Magdalena","utm3":"Chirigpunta, Huacataz Laparpampa, Santa Maria Magdalena","seccion":"Sección 1","area":"Área 1","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"CC.CC","codigopersonal":"P71-CAJ-CC-DIAG-TEC-DE-CAMPO","objeto":"en materia técnica para el levantamiento topográfico y recopilación de información con el fin de elaborar los diagnósticos fisicos legales y socio ambientales de Comunidades Campesinas – CC.CC."},
{"departamento":"Cajamarca","Nro":9,"PROCEDIMIENTO":"DESLINDE Y TITULACION CC.CC","personal":"TECNICO DE CAMPO 2","orden":2,"provincia":"San Marcos","utm1":"Socchagon","utm2":"Socchagon","utm3":"Socchagon","seccion":"Sección 2","area":"Área 2","GRUPO":"DESLINDE - PERSONAL CAMPO","tipopredio":"CC.CC","codigopersonal":"P67-CAJ-PRI-CAMP-TEC-CAMPO","objeto":"en materia técnica para el deslinde y titulación de CC.CC."},
{"departamento":"Cajamarca","Nro":17,"PROCEDIMIENTO":"DIAGNOSTICO CC.CC","personal":"TECNICO DE CAMPO 2","orden":2,"provincia":"Contumaza, San Miguel","utm1":"San Juan de Llallan, San Antonio de Ojos, Calquis","utm2":"San Juan de LLallan, San Antonio de Ojos, Calquis","utm3":"San Juan de Llallan, San Antonio de Ojos, Calquis","seccion":"Sección 2","area":"Área 2","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"CC.CC","codigopersonal":"P71-CAJ-CC-DIAG-TEC-DE-CAMPO","objeto":"en materia técnica para el levantamiento topográfico y recopilación de información con el fin de elaborar los diagnósticos fisicos legales y socio ambientales de Comunidades Campesinas – CC.CC."},
{"departamento":"Cajamarca","Nro":10,"PROCEDIMIENTO":"DESLINDE Y TITULACION CC.CC","personal":"TECNICO DE CAMPO 3","orden":3,"provincia":"San Marcos, Cajamarca","utm1":"Pomarongo Shillabamba, Cushunga","utm2":"Pomarongo Shillabamba, Cushunga","utm3":"Pomarongo Shillabamba, Cushunga","seccion":"Sección 3","area":"Área 3","GRUPO":"DESLINDE - PERSONAL CAMPO","tipopredio":"CC.CC","codigopersonal":"P67-CAJ-PRI-CAMP-TEC-CAMPO","objeto":"en materia técnica para el deslinde y titulación de CC.CC."},
{"departamento":"Cajamarca","Nro":18,"PROCEDIMIENTO":"DIAGNOSTICO CC.CC","personal":"TECNICO EN ENFERMERIA 1","orden":1,"provincia":"Cajamarca, Contumaza, San Miguel","utm1":"Chirigpunta, Huacataz Laparpampa, Santa Maria Magdalena, San Juan de LLallan, San Antonio de Ojos, Calquis, San Benito, Socchagon, Pomarongo Shillabamba, Cushunga","utm2":"Chirigpunta, Huacataz Laparpampa, Santa Maria Magdalena, San Juan de LLallan, San Antonio de Ojos, Calquis, San Benito, Socchagon, Pomarongo Shillabamba, Cushunga","utm3":"Chirigpunta, Huacataz Laparpampa, Santa Maria Magdalena, San Juan de LLallan, San Antonio de Ojos, Calquis, San Benito, Socchagon, Pomarongo Shillabamba, Cushunga","seccion":"","area":"","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"CC.CC","codigopersonal":"P69-CAJ-CC-DIAG-TEC-EN-ENF","objeto":"en materia de salud, en la aplicación del protocolo para la implementación de medidas de vigilancia, prevención y control frente al Covid-19 en la actividad de titulación  de la propiedad agraria y  de catastro rural"},
{"departamento":"Cajamarca","Nro":19,"PROCEDIMIENTO":"DIAGNOSTICO CC.CC","personal":"TECNICO REGISTRAL 1","orden":1,"provincia":"Cajamarca, contumaza, San miguel","utm1":"Chirigpunta, Huacataz Laparpampa, Santa Maria Magdalena, San Juan de LLallan, San Antonio de Ojos, Calquis","utm2":"Chirigpunta, Huacataz Laparpampa, Santa Maria Magdalena, San Juan de LLallan, San Antonio de Ojos, Calquis","utm3":"Chirigpunta, Huacataz Laparpampa, Santa Maria Magdalena, San Juan de LLallan, San Antonio de Ojos, Calquis","seccion":"","area":"","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"CC.CC","codigopersonal":"P74-CAJ-CC-DIAG-TEC-REGISTR","objeto":"en materia legal para la recopilación de información registral existente en la SUNARP para el procedimiento de deslinde y titulación de CC.CC."},
{"departamento":"Cajamarca","Nro":20,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"ABOGADO DIAGNOSTICO 1","orden":1,"provincia":"Chota","utm1":"Chadin, Paccha, Conchan 1","utm2":"Chadin, Paccha, Conchan 1","utm3":"Chadin, Paccha, Conchan 1","seccion":"Sección 1","area":"Área 1","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P89-CAJ-PRI-DIAG-ABG-DIAG","objeto":"en materia legal para la elaboración de informes de diagnóstico fisico legal y socio ambiental de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":22,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"ABOGADO DIAGNOSTICO 2","orden":3,"provincia":"Chota","utm1":"San Juan de Cutervo, Anguia, Santo Tomas 1","utm2":"San Juan de Cutervo, Anguia, Santo Tomas 1","utm3":"San Juan de Cutervo, Anguia, Santo Tomas 1","seccion":"Sección 3","area":"Área 3","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P89-CAJ-PRI-DIAG-ABG-DIAG","objeto":"en materia legal para la elaboración de informes de diagnóstico fisico legal y socio ambiental de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":21,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"ABOGADO DIAGNOSTICO 3","orden":2,"provincia":"Cutervo","utm1":"Toribio Casanova 1, Toribio Casanova 2, Callayuc ","utm2":"Toribio Casanova 1, Toribio Casanova 2, Callayuc ","utm3":"Toribio Casanova 1, Toribio Casanova 2, Callayuc ","seccion":"Sección 2","area":"Área 2","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P89-CAJ-PRI-DIAG-ABG-DIAG","objeto":"en materia legal para la elaboración de informes de diagnóstico fisico legal y socio ambiental de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":23,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"ABOGADO DIAGNOSTICO 4","orden":4,"provincia":"Cutervo","utm1":"Cujillo, Querocotillo, Pimpingos","utm2":"Cujillo, Querocotillo, Pimpingos","utm3":"Cujillo, Querocotillo, Pimpingos","seccion":"Sección 4","area":"Área 4","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P89-CAJ-PRI-DIAG-ABG-DIAG","objeto":"en materia legal para la elaboración de informes de diagnóstico fisico legal y socio ambiental de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":24,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"ABOGADO DIAGNOSTICO 5","orden":5,"provincia":"Chota, Cutervo","utm1":"La Ramada, Socota, Querocoto","utm2":"La Ramada, Socota, Querocoto","utm3":"La Ramada, Socota, Querocoto","seccion":"Sección 5","area":"Área 5","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P89-CAJ-PRI-DIAG-ABG-DIAG","objeto":"en materia legal para la elaboración de informes de diagnóstico fisico legal y socio ambiental de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":25,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"ESPECIALISTA CAD/GIS 1","orden":1,"provincia":"Chota","utm1":"Chadin, Paccha, Conchan 1","utm2":"Chadin, Paccha, Conchan 1","utm3":"Chadin, Paccha, Conchan 1","seccion":"Sección 1","area":"Área 1","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P88-CAJ-PRI-DIAG-ESP-CADGIS","objeto":"especializado en CAD / GIS para recopilar, procesar y analizar información de las bases gráficas con fines de diagnóstico físico legal de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":26,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"ESPECIALISTA CAD/GIS 2","orden":2,"provincia":"Cutervo","utm1":"Toribio Casanova 1, Toribio Casanova 2, Callayuc ","utm2":"Toribio Casanova 1, Toribio Casanova 2, Callayuc ","utm3":"Toribio Casanova 1, Toribio Casanova 2, Callayuc ","seccion":"Sección 2","area":"Área 2","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P88-CAJ-PRI-DIAG-ESP-CADGIS","objeto":"especializado en CAD / GIS para recopilar, procesar y analizar información de las bases gráficas con fines de diagnóstico físico legal de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":27,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"ESPECIALISTA CAD/GIS 3","orden":3,"provincia":"Chota","utm1":"San Juan de Cutervo, Anguia, Santo Tomas 1","utm2":"San Juan de Cutervo, Anguia, Santo Tomas 1","utm3":"San Juan de Cutervo, Anguia, Santo Tomas 1","seccion":"Sección 3","area":"Área 3","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P88-CAJ-PRI-DIAG-ESP-CADGIS","objeto":"especializado en CAD / GIS para recopilar, procesar y analizar información de las bases gráficas con fines de diagnóstico físico legal de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":28,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"ESPECIALISTA CAD/GIS 4","orden":4,"provincia":"Cutervo","utm1":"Cujillo, Querocotillo, Pimpingos","utm2":"Cujillo, Querocotillo, Pimpingos","utm3":"Cujillo, Querocotillo, Pimpingos","seccion":"Sección 4","area":"Área 4","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P88-CAJ-PRI-DIAG-ESP-CADGIS","objeto":"especializado en CAD / GIS para recopilar, procesar y analizar información de las bases gráficas con fines de diagnóstico físico legal de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":29,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"ESPECIALISTA CAD/GIS 5","orden":5,"provincia":"Chota, Cutervo","utm1":"La Ramada, Socota, Querocoto","utm2":"La Ramada, Socota, Querocoto","utm3":"La Ramada, Socota, Querocoto","seccion":"Sección 5","area":"Área 5","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P88-CAJ-PRI-DIAG-ESP-CADGIS","objeto":"especializado en CAD / GIS para recopilar, procesar y analizar información de las bases gráficas con fines de diagnóstico físico legal de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":30,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"INGENIERO DIAGNOSTICO 1","orden":1,"provincia":"Chota","utm1":"Chadin, Paccha, Conchan 1","utm2":"Chadin, Paccha, Conchan 1","utm3":"Chadin, Paccha, Conchan 1","seccion":"Sección 1","area":"Área 1","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P87-CAJ-PRI-DIAG-ING-DIAG","objeto":"en materia técnica para la elaboración de informes de diagnóstico fisico legal y socio ambiental de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":32,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"INGENIERO DIAGNOSTICO 2","orden":3,"provincia":"Chota","utm1":"San Juan de Cutervo, Anguia, Santo Tomas 1","utm2":"San Juan de Cutervo, Anguia, Santo Tomas 1","utm3":"San Juan de Cutervo, Anguia, Santo Tomas 1","seccion":"Sección 3","area":"Área 3","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P87-CAJ-PRI-DIAG-ING-DIAG","objeto":"en materia técnica para la elaboración de informes de diagnóstico fisico legal y socio ambiental de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":34,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"INGENIERO DIAGNOSTICO 3","orden":5,"provincia":"Chota, cutervo","utm1":"La Ramada, Socota, Querocoto","utm2":"La Ramada, Socota, Querocoto","utm3":"La Ramada, Socota, Querocoto","seccion":"Sección 5","area":"Área 5","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P87-CAJ-PRI-DIAG-ING-DIAG","objeto":"en materia técnica para la elaboración de informes de diagnóstico fisico legal y socio ambiental de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":31,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"INGENIERO DIAGNOSTICO 4","orden":2,"provincia":"Cutervo","utm1":"Toribio Casanova 1, Toribio Casanova 2, Callayuc ","utm2":"Toribio Casanova 1, Toribio Casanova 2, Callayuc ","utm3":"Toribio Casanova 1, Toribio Casanova 2, Callayuc ","seccion":"Sección 2","area":"Área 2","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P87-CAJ-PRI-DIAG-ING-DIAG","objeto":"en materia técnica para la elaboración de informes de diagnóstico fisico legal y socio ambiental de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":33,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"INGENIERO DIAGNOSTICO 5","orden":4,"provincia":"Cutervo","utm1":"Cujillo, Querocotillo, Pimpingos","utm2":"Cujillo, Querocotillo, Pimpingos","utm3":"Cujillo, Querocotillo, Pinmpingos","seccion":"Sección 4","area":"Área 4","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P87-CAJ-PRI-DIAG-ING-DIAG","objeto":"en materia técnica para la elaboración de informes de diagnóstico fisico legal y socio ambiental de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":35,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"TECNICO DE CAMPO 1","orden":1,"provincia":"Chota","utm1":"Chadin, Paccha, Conchan 1","utm2":"Chadin, Paccha, Conchan 1","utm3":"Chadin, Paccha, Conchan 1","seccion":"Sección 1","area":"Área 1","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P86-CAJ-PRI-DIAG-TEC-DE-CAMPO","objeto":"en materia técnica para el levantamiento topográfico y recopilación de información con el fin de elaborar los diagnósticos fisicos legales y socio ambientales de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":36,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"TECNICO DE CAMPO 2","orden":2,"provincia":"Cutervo","utm1":"Toribio Casanova 1, Toribio Casanova 2, Callayuc ","utm2":"Toribio Casanova 1, Toribio Casanova 2, Callayuc ","utm3":"Toribio Casanova 1, Toribio Casanova 2, Callayuc ","seccion":"Sección 2","area":"Área 2","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P86-CAJ-PRI-DIAG-TEC-DE-CAMPO","objeto":"en materia técnica para el levantamiento topográfico y recopilación de información con el fin de elaborar los diagnósticos fisicos legales y socio ambientales de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":37,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"TECNICO DE CAMPO 3","orden":3,"provincia":"Chota","utm1":"San Juan de Cutervo, Anguia, Santo Tomas 1","utm2":"San Juan de Cutervo, Anguia, Santo Tomas 1","utm3":"San Juan de Cutervo, Anguia, SantoTomas 1","seccion":"Sección 3","area":"Área 3","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P86-CAJ-PRI-DIAG-TEC-DE-CAMPO","objeto":"en materia técnica para el levantamiento topográfico y recopilación de información con el fin de elaborar los diagnósticos fisicos legales y socio ambientales de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":38,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"TECNICO DE CAMPO 4","orden":4,"provincia":"Cutervo","utm1":"Cujillo, Querocotillo, Pimpingos","utm2":"Cujillo, Querocotillo, Pimpingos","utm3":"Cujillo, Querocotillo, Pimpingos","seccion":"Sección 4","area":"Área 4","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P86-CAJ-PRI-DIAG-TEC-DE-CAMPO","objeto":"en materia técnica para el levantamiento topográfico y recopilación de información con el fin de elaborar los diagnósticos fisicos legales y socio ambientales de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":39,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"TECNICO DE CAMPO 5","orden":5,"provincia":"Chota, Cutervo","utm1":"La Ramada, Socota, Querocoto","utm2":"La Ramada, Socota, Querocoto","utm3":"La Ramada, Socota, Querocoto","seccion":"Sección 5","area":"Área 5","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P86-CAJ-PRI-DIAG-TEC-DE-CAMPO","objeto":"en materia técnica para el levantamiento topográfico y recopilación de información con el fin de elaborar los diagnósticos fisicos legales y socio ambientales de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":40,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"TECNICO REGISTRAL 1","orden":1,"provincia":"Chota","utm1":"Chadin, Paccha, Conchan 1","utm2":"Chadin, Paccha, Conchan 1","utm3":"Chadin, Paccha, Conchan 1","seccion":"Sección 1","area":"Área 1","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P90-CAJ-PRI-DIAG-TEC-REGISTR","objeto":"en materia legal para la recopilación de información registral existente en la SUNARP para el procedimiento de formalización y titulación de PRI"},
{"departamento":"Cajamarca","Nro":41,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"TECNICO REGISTRAL 2","orden":2,"provincia":"Cutervo","utm1":"Toribio Casanova 1, Toribio Casanova 2, Callayuc ","utm2":"Toribio Casanova 1, Toribio Casanova 2, Callayuc ","utm3":"Toribio Casanova 1, Toribio Casanova 2, Callayuc ","seccion":"Sección 2","area":"Área 2","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P90-CAJ-PRI-DIAG-TEC-REGISTR","objeto":"en materia legal para la recopilación de información registral existente en la SUNARP para el procedimiento de formalización y titulación de PRI"},
{"departamento":"Cajamarca","Nro":42,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"TECNICO REGISTRAL 3","orden":3,"provincia":"Chota","utm1":"San Juan de Cutervo, Anguia, Santo Tomas 1","utm2":"San Juan de Cutervo, Anguia, Santo Tomas 1","utm3":"San Juan de Cutervo, Anguia, Santo Tomas 1","seccion":"Sección 3","area":"Área 3","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P90-CAJ-PRI-DIAG-TEC-REGISTR","objeto":"en materia legal para la recopilación de información registral existente en la SUNARP para el procedimiento de formalización y titulación de PRI"},
{"departamento":"Cajamarca","Nro":43,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"TECNICO REGISTRAL 4","orden":4,"provincia":"Cutervo","utm1":"Cujillo, Querocotillo, Pimpingos","utm2":"Cujillo, Querocotillo, Pimpingos","utm3":"Cujillo, Querocotillo, Pimpingos","seccion":"Sección 4","area":"Área 4","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P90-CAJ-PRI-DIAG-TEC-REGISTR","objeto":"en materia legal para la recopilación de información registral existente en la SUNARP para el procedimiento de formalización y titulación de PRI"},
{"departamento":"Cajamarca","Nro":44,"PROCEDIMIENTO":"DIAGNOSTICO PRI","personal":"TECNICO REGISTRAL 5","orden":5,"provincia":"Chota, Cutervo","utm1":"La Ramada, Socota, Querocoto","utm2":"La Ramada, Socota, Querocoto","utm3":"La Ramada, Socota, Querocoto","seccion":"Sección 5","area":"Área 5","GRUPO":"PERS. DIAGNOSTICO/INF. PRELIMINAR","tipopredio":"PRI","codigopersonal":"P90-CAJ-PRI-DIAG-TEC-REGISTR","objeto":"en materia legal para la recopilación de información registral existente en la SUNARP para el procedimiento de formalización y titulación de PRI"},
{"departamento":"Cajamarca","Nro":130,"PROCEDIMIENTO":"PERSONAL GANINETE PRI","personal":"ABOGADO CALIFICADOR 1","orden":1,"provincia":"Celendin","utm1":"Pallan","utm2":"Pallan","utm3":"Pallan","seccion":"","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P91-CAJ-PRI-GAB-ABG-CALIF","objeto":"en materia legal para efectuar la calificación de expedientes de formalización y titulación de predios rurales"},
{"departamento":"Cajamarca","Nro":132,"PROCEDIMIENTO":"PERSONAL GANINETE PRI","personal":"ABOGADO CALIFICADOR 2","orden":3,"provincia":"Celendin","utm1":"Cortegana","utm2":"Cortegana","utm3":"Cortegana","seccion":"","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P91-CAJ-PRI-GAB-ABG-CALIF","objeto":"en materia legal para efectuar la calificación de expedientes de formalización y titulación de predios rurales"},
{"departamento":"Cajamarca","Nro":133,"PROCEDIMIENTO":"PERSONAL GANINETE PRI","personal":"ABOGADO CALIFICADOR 3","orden":4,"provincia":"Celendin","utm1":"Chumuc, Chalan","utm2":"Chumuc, Chalan","utm3":"Chumuc, Chalan","seccion":"","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P91-CAJ-PRI-GAB-ABG-CALIF","objeto":"en materia legal para efectuar la calificación de expedientes de formalización y titulación de predios rurales"},
{"departamento":"Cajamarca","Nro":134,"PROCEDIMIENTO":"PERSONAL GANINETE PRI","personal":"ABOGADO CALIFICADOR 4","orden":5,"provincia":"Contumaza","utm1":"Contumaza","utm2":"Contumaza","utm3":"Contumaza","seccion":"","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P91-CAJ-PRI-GAB-ABG-CALIF","objeto":"en materia legal para efectuar la calificación de expedientes de formalización y titulación de predios rurales"},
{"departamento":"Cajamarca","Nro":131,"PROCEDIMIENTO":"PERSONAL GANINETE PRI","personal":"ABOGADO CALIFICADOR 5","orden":2,"provincia":"San Miguel, San Marcos","utm1":"Cochan, Catilluc, LLapa, Matibamba","utm2":"Cochan, Catilluc, LLapa, Matibamba","utm3":"Cochan, Catilluc, LLapa, Matibamba","seccion":"","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P91-CAJ-PRI-GAB-ABG-CALIF","objeto":"en materia legal para efectuar la calificación de expedientes de formalización y titulación de predios rurales"},
{"departamento":"Cajamarca","Nro":45,"PROCEDIMIENTO":"TITULACION PRI","personal":"ABOGADO DE CAMPO 1","orden":1,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 1","area":"Área 1 - 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P76-CAJ-PRI-CAMP-ABG-DE-CAMPO","objeto":"en materia legal para verificar y evaluar documentación legal obtenida en campo y control de calidad de la ficha catastral "},
{"departamento":"Cajamarca","Nro":53,"PROCEDIMIENTO":"TITULACION PRI","personal":"ABOGADO DE CAMPO 10","orden":8,"provincia":"San Miguel","utm1":"Catilluc","utm2":"Cochan","utm3":"Llapa","seccion":"Sección 8","area":"Área 1 - 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P76-CAJ-PRI-CAMP-ABG-DE-CAMPO","objeto":"en materia legal para verificar y evaluar documentación legal obtenida en campo y control de calidad de la ficha catastral "},
{"departamento":"Cajamarca","Nro":47,"PROCEDIMIENTO":"TITULACION PRI","personal":"ABOGADO DE CAMPO 2","orden":2,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 2","area":"Área 1 - 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P76-CAJ-PRI-CAMP-ABG-DE-CAMPO","objeto":"en materia legal para verificar y evaluar documentación legal obtenida en campo y control de calidad de la ficha catastral "},
{"departamento":"Cajamarca","Nro":48,"PROCEDIMIENTO":"TITULACION PRI","personal":"ABOGADO DE CAMPO 3","orden":3,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 3","area":"Área 1 - 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P76-CAJ-PRI-CAMP-ABG-DE-CAMPO","objeto":"en materia legal para verificar y evaluar documentación legal obtenida en campo y control de calidad de la ficha catastral "},
{"departamento":"Cajamarca","Nro":49,"PROCEDIMIENTO":"TITULACION PRI","personal":"ABOGADO DE CAMPO 4","orden":4,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 4","area":"Área 1 - 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P76-CAJ-PRI-CAMP-ABG-DE-CAMPO","objeto":"en materia legal para verificar y evaluar documentación legal obtenida en campo y control de calidad de la ficha catastral "},
{"departamento":"Cajamarca","Nro":50,"PROCEDIMIENTO":"TITULACION PRI","personal":"ABOGADO DE CAMPO 5","orden":5,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 5","area":"Área 1 - 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P76-CAJ-PRI-CAMP-ABG-DE-CAMPO","objeto":"en materia legal para verificar y evaluar documentación legal obtenida en campo y control de calidad de la ficha catastral "},
{"departamento":"Cajamarca","Nro":51,"PROCEDIMIENTO":"TITULACION PRI","personal":"ABOGADO DE CAMPO 6","orden":6,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 6","area":"Área 1 - 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P76-CAJ-PRI-CAMP-ABG-DE-CAMPO","objeto":"en materia legal para verificar y evaluar documentación legal obtenida en campo y control de calidad de la ficha catastral "},
{"departamento":"Cajamarca","Nro":46,"PROCEDIMIENTO":"TITULACION PRI","personal":"ABOGADO DE CAMPO 7","orden":10,"provincia":"Contumaza","utm1":"Contumaza, Matibamba","utm2":"Contumaza, Matibamba","utm3":"Contumaza, Matibamba","seccion":"Sección 10","area":"Área 1-5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P76-CAJ-PRI-CAMP-ABG-DE-CAMPO","objeto":"en materia legal para verificar y evaluar documentación legal obtenida en campo y control de calidad de la ficha catastral "},
{"departamento":"Cajamarca","Nro":54,"PROCEDIMIENTO":"TITULACION PRI","personal":"ABOGADO DE CAMPO 8","orden":9,"provincia":"Contumaza","utm1":"Contumaza, Matibamba","utm2":"Contumaza, Matibamba","utm3":"Contumaza, Matibamba","seccion":"Sección 9","area":"Área 1-5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P76-CAJ-PRI-CAMP-ABG-DE-CAMPO","objeto":"en materia legal para verificar y evaluar documentación legal obtenida en campo y control de calidad de la ficha catastral "},
{"departamento":"Cajamarca","Nro":52,"PROCEDIMIENTO":"TITULACION PRI","personal":"ABOGADO DE CAMPO 9","orden":7,"provincia":"San Miguel","utm1":"Catilluc","utm2":"Cochan","utm3":"Llapa","seccion":"Sección 7","area":"Área 1 - 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P76-CAJ-PRI-CAMP-ABG-DE-CAMPO","objeto":"en materia legal para verificar y evaluar documentación legal obtenida en campo y control de calidad de la ficha catastral "},
{"departamento":"Cajamarca","Nro":140,"PROCEDIMIENTO":"PERSONAL GANINETE PRI","personal":"ABOGADO RESPONSABLE DE SECTOR 1","orden":1,"provincia":"Cajamarca","utm1":"","utm2":"","utm3":"","seccion":"","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P92-CAJ-PRI-GAB-ABG-RSP-DE-SECT","objeto":"en materia legal para coordinar, monitorear y efecutar el seguimiento del procedimiento de formalización y titulación de PRI y  CC.CC"},
{"departamento":"Cajamarca","Nro":55,"PROCEDIMIENTO":"PERSONAL CAMPO PRI","personal":"ARQUEOLOGO 1","orden":1,"provincia":"Celendin,San Miguel,Contumaza","utm1":"Celendin, San Miguel, Contumaza","utm2":"Celendin, San Miguel, Contumaza","utm3":"Celendin, San Miguel, Contumaza","seccion":"Sección 1 al 10","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P81-CAJ-PRI-CAMP-ARQ","objeto":"para la identificacion de patrimonio cultural de la nación o zonas arqueologicas en campo"},
{"departamento":"Cajamarca","Nro":135,"PROCEDIMIENTO":"PERSONAL GANINETE PRI","personal":"ASISTENTE ADMINISTRATIVO 1","orden":1,"provincia":"Cajamarca","utm1":"Cajamarca","utm2":"Cajamarca","utm3":"Cajamarca","seccion":"","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P93-CAJ-PRI-GAB-ASST-ADM","objeto":"en materia administrativa para realizar actividades de apoyo en la gestión administrativa a los grupos de trabajo supervisado"},
{"departamento":"Cajamarca","Nro":136,"PROCEDIMIENTO":"PERSONAL GANINETE PRI","personal":"DIGITADOR 1","orden":1,"provincia":"Cajamarca","utm1":"Pallan, Cortegana, Chalan, Chumuch","utm2":"Pallan, Cortegana, Chalan, Chumuch","utm3":"Pallan, Cortegana, Chalan, Chumuch","seccion":"","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P94-CAJ-PRI-GAB-DIGITADOR","objeto":"para sistematización de información de base de datos"},
{"departamento":"Cajamarca","Nro":137,"PROCEDIMIENTO":"PERSONAL GANINETE PRI","personal":"DIGITADOR 2","orden":2,"provincia":"Cajamarca","utm1":"Cochan, Catilluc, LLapa, Contumaza, Matibamba","utm2":"Cochan, Catilluc, LLapa, Contumaza, Matibamba","utm3":"Cochan, Catilluc, LLapa, Contumaza, Matibamba","seccion":"","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P94-CAJ-PRI-GAB-DIGITADOR","objeto":"para sistematización de información de base de datos"},
{"departamento":"Cajamarca","Nro":138,"PROCEDIMIENTO":"PERSONAL GANINETE PRI","personal":"ESPECIALISTA CAD/GIS 1","orden":1,"provincia":"Celendin","utm1":"Pallan, Cortegana, Chalan, Chumuch","utm2":"Pallan, Cortegana, Chalan, Chumuch","utm3":"Pallan, Cortegana, Chalan, Chumuch","seccion":"","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P95-CAJ-PRI-GAB-ESP-CADGIS","objeto":"en CAD GIS en gabinete para la administración y ejecución de la base gráfica y base de datos"},
{"departamento":"Cajamarca","Nro":139,"PROCEDIMIENTO":"PERSONAL GANINETE PRI","personal":"ESPECIALISTA CAD/GIS 1-A","orden":2,"provincia":"San Miguel, San Marcos","utm1":"Cochan, Catilluc,LLapa, Contumaza, Matibamba","utm2":"Cochan, Catilluc, LLapa, Contumaza, Matibamba","utm3":"Cochan, Catilluc, LLapa, Contumaza, Matibamba","seccion":"","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P95-CAJ-PRI-GAB-ESP-CADGIS","objeto":"en CAD GIS en gabinete para la administración y ejecución de la base gráfica y base de datos"},
{"departamento":"Cajamarca","Nro":56,"PROCEDIMIENTO":"TITULACION PRI","personal":"ESPECIALISTA GIS CAMPO 1","orden":1,"provincia":"Celendin","utm1":"Pallan, Cortegana","utm2":"Pallan, Cortegana","utm3":"Pallan, Cortegana","seccion":"Sección 1 al 10","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P80-CAJ-PRI-CAMP-ESP-GIS-CAMPO","objeto":"especializado en CAD GIS en campo para el procesamiento de datos GPS/GNSS de PRI"},
{"departamento":"Cajamarca","Nro":57,"PROCEDIMIENTO":"TITULACION PRI","personal":"ESPECIALISTA GIS CAMPO 2","orden":2,"provincia":"Celendin","utm1":"Chalan, Chumuch","utm2":"Chalan, Chumuch","utm3":"Chalan, Chumuch","seccion":"Sección 1 al 10","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P80-CAJ-PRI-CAMP-ESP-GIS-CAMPO","objeto":"especializado en CAD GIS en campo para el procesamiento de datos GPS/GNSS de PRI"},
{"departamento":"Cajamarca","Nro":58,"PROCEDIMIENTO":"TITULACION PRI","personal":"ESPECIALISTA GIS CAMPO 3","orden":3,"provincia":"San Miguel","utm1":"Catilluc, Cochan","utm2":"Catilluc, Cochan","utm3":"Catilluc, Cochan","seccion":"Sección 1 al 10","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P80-CAJ-PRI-CAMP-ESP-GIS-CAMPO","objeto":"especializado en CAD GIS en campo para el procesamiento de datos GPS/GNSS de PRI"},
{"departamento":"Cajamarca","Nro":59,"PROCEDIMIENTO":"TITULACION PRI","personal":"ESPECIALISTA GIS CAMPO 4","orden":4,"provincia":"Contumaza","utm1":"Contumaza","utm2":"Contumaza","utm3":"Contumaza","seccion":"Sección 1 al 10","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P80-CAJ-PRI-CAMP-ESP-GIS-CAMPO","objeto":"especializado en CAD GIS en campo para el procesamiento de datos GPS/GNSS de PRI"},
{"departamento":"Cajamarca","Nro":60,"PROCEDIMIENTO":"TITULACION PRI","personal":"ESPECIALISTA GIS CAMPO 5","orden":5,"provincia":"San Miguel, San Marcos","utm1":"LLapa, Matibamba","utm2":"LLapa, Matibamba","utm3":"LLapa, Matibamba","seccion":"Sección 1 al 10","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P80-CAJ-PRI-CAMP-ESP-GIS-CAMPO","objeto":"especializado en CAD GIS en campo para el procesamiento de datos GPS/GNSS de PRI"},
{"departamento":"Cajamarca","Nro":61,"PROCEDIMIENTO":"PERSONAL CAMPO PRI","personal":"ESPECIALISTA SOCIAL Y RECEPTOR DE MANIFIESTOS 1","orden":1,"provincia":"Celendin, Contumaza","utm1":"Pallan, Cortegana, CC.CC. San Benito","utm2":"Pallan, Cortegana, CC.CC. San Benito","utm3":"Pallan, Cortegana, CC.CC. San benito","seccion":"Sección 1 al 10","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P77-CAJ-PRI-CAMP-ESP-SOCIAL-Y-RECP-DE-MNFTS","objeto":"en materia social para las actividades en campo y/o gabinete"},
{"departamento":"Cajamarca","Nro":62,"PROCEDIMIENTO":"PERSONAL CAMPO PRI","personal":"ESPECIALISTA SOCIAL Y RECEPTOR DE MANIFIESTOS 2","orden":2,"provincia":"Celendin, San Miguel, San Marcos","utm1":"Chalan, Catilluc, CC.CC. Socchagon","utm2":"Chalan, Catilluc, CC.CC. Socchagon","utm3":"Chalan, Catilluc, CC.CC. Socchagon","seccion":"Sección 1 al 10","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P77-CAJ-PRI-CAMP-ESP-SOCIAL-Y-RECP-DE-MNFTS","objeto":"en materia social para las actividades en campo y/o gabinete"},
{"departamento":"Cajamarca","Nro":63,"PROCEDIMIENTO":"PERSONAL CAMPO PRI","personal":"ESPECIALISTA SOCIAL Y RECEPTOR DE MANIFIESTOS 3","orden":3,"provincia":"Celendin, Contumaza, San Marcos","utm1":"Yapa, Cochan, CC.CC. Cushunga","utm2":"LLapa, Cochan, CC.CC. Cushunga","utm3":"LLapa, Cocchan, CC.CC. Cushunga","seccion":"Sección 1 al 10","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P77-CAJ-PRI-CAMP-ESP-SOCIAL-Y-RECP-DE-MNFTS","objeto":"en materia social para las actividades en campo y/o gabinete"},
{"departamento":"Cajamarca","Nro":64,"PROCEDIMIENTO":"PERSONAL CAMPO PRI","personal":"ESPECIALISTA SOCIAL Y RECEPTOR DE MANIFIESTOS 4","orden":4,"provincia":"Celendin, Contumaza, San Marcos","utm1":"Chumuch, Contumaza, CC.CC. Pomarongo Shillabamba","utm2":"Chumuch, Contumaza, CC.CC. Pomarongo Shillabamba","utm3":"Chumuch, Contumaza, CC.CC. Pomarongo Shillabamba","seccion":"Sección 1 al 10","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P77-CAJ-PRI-CAMP-ESP-SOCIAL-Y-RECP-DE-MNFTS","objeto":"en materia social para las actividades en campo y/o gabinete"},
{"departamento":"Cajamarca","Nro":65,"PROCEDIMIENTO":"PERSONAL CAMPO PRI","personal":"ESPECIALISTA SOCIAL Y RECEPTOR DE MANIFIESTOS 5","orden":5,"provincia":"San Marcos","utm1":"Matibamba","utm2":"Matibamba","utm3":"Matibamba","seccion":"Sección 1 al 10","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P77-CAJ-PRI-CAMP-ESP-SOCIAL-Y-RECP-DE-MNFTS","objeto":"en materia social para las actividades en campo y/o gabinete"},
{"departamento":"Cajamarca","Nro":66,"PROCEDIMIENTO":"TITULACION PRI","personal":"INGENIERO EN CIENCIAS AGRARIAS (LIDER DE ETE) Y AMBIENTAL 1","orden":1,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 1","area":"Área 1 - 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P78-CAJ-PRI-CAMP-ING-EN-CS-AGR-LDR-DE-ETE-Y-AMB","objeto":"materia técnica para coordinar, monitorear y efectuar el seguimiento al equipo técnico especializado en actividades de campo de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":67,"PROCEDIMIENTO":"TITULACION PRI","personal":"INGENIERO EN CIENCIAS AGRARIAS (LIDER DE ETE) Y AMBIENTAL 10","orden":10,"provincia":"Contumaza","utm1":"Contumaza, Matibamba","utm2":"Contumaza, Matibamba","utm3":"Contumaza, Matibamba","seccion":"Sección 10","area":"Área 1-5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P78-CAJ-PRI-CAMP-ING-EN-CS-AGR-LDR-DE-ETE-Y-AMB","objeto":"materia técnica para coordinar, monitorear y efectuar el seguimiento al equipo técnico especializado en actividades de campo de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":68,"PROCEDIMIENTO":"TITULACION PRI","personal":"INGENIERO EN CIENCIAS AGRARIAS (LIDER DE ETE) Y AMBIENTAL 2","orden":2,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 2","area":"Área 1 - 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P78-CAJ-PRI-CAMP-ING-EN-CS-AGR-LDR-DE-ETE-Y-AMB","objeto":"materia técnica para coordinar, monitorear y efectuar el seguimiento al equipo técnico especializado en actividades de campo de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":69,"PROCEDIMIENTO":"TITULACION PRI","personal":"INGENIERO EN CIENCIAS AGRARIAS (LIDER DE ETE) Y AMBIENTAL 3","orden":3,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 3","area":"Área 1 - 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P78-CAJ-PRI-CAMP-ING-EN-CS-AGR-LDR-DE-ETE-Y-AMB","objeto":"materia técnica para coordinar, monitorear y efectuar el seguimiento al equipo técnico especializado en actividades de campo de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":70,"PROCEDIMIENTO":"TITULACION PRI","personal":"INGENIERO EN CIENCIAS AGRARIAS (LIDER DE ETE) Y AMBIENTAL 4","orden":4,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 4","area":"Área 1 - 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P78-CAJ-PRI-CAMP-ING-EN-CS-AGR-LDR-DE-ETE-Y-AMB","objeto":"materia técnica para coordinar, monitorear y efectuar el seguimiento al equipo técnico especializado en actividades de campo de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":71,"PROCEDIMIENTO":"TITULACION PRI","personal":"INGENIERO EN CIENCIAS AGRARIAS (LIDER DE ETE) Y AMBIENTAL 5","orden":5,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 5","area":"Área 1 - 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P78-CAJ-PRI-CAMP-ING-EN-CS-AGR-LDR-DE-ETE-Y-AMB","objeto":"materia técnica para coordinar, monitorear y efectuar el seguimiento al equipo técnico especializado en actividades de campo de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":72,"PROCEDIMIENTO":"TITULACION PRI","personal":"INGENIERO EN CIENCIAS AGRARIAS (LIDER DE ETE) Y AMBIENTAL 6","orden":6,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 6","area":"Área 1 - 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P78-CAJ-PRI-CAMP-ING-EN-CS-AGR-LDR-DE-ETE-Y-AMB","objeto":"materia técnica para coordinar, monitorear y efectuar el seguimiento al equipo técnico especializado en actividades de campo de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":73,"PROCEDIMIENTO":"TITULACION PRI","personal":"INGENIERO EN CIENCIAS AGRARIAS (LIDER DE ETE) Y AMBIENTAL 7","orden":7,"provincia":"San Miguel","utm1":"Catilluc","utm2":"Cochan","utm3":"Llapa","seccion":"Sección 7","area":"Área 1 - 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P78-CAJ-PRI-CAMP-ING-EN-CS-AGR-LDR-DE-ETE-Y-AMB","objeto":"materia técnica para coordinar, monitorear y efectuar el seguimiento al equipo técnico especializado en actividades de campo de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":74,"PROCEDIMIENTO":"TITULACION PRI","personal":"INGENIERO EN CIENCIAS AGRARIAS (LIDER DE ETE) Y AMBIENTAL 8","orden":8,"provincia":"San Miiguel","utm1":"Catilluc","utm2":"Cochan","utm3":"Llapa","seccion":"Sección 8","area":"Área 1 - 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P78-CAJ-PRI-CAMP-ING-EN-CS-AGR-LDR-DE-ETE-Y-AMB","objeto":"materia técnica para coordinar, monitorear y efectuar el seguimiento al equipo técnico especializado en actividades de campo de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":75,"PROCEDIMIENTO":"TITULACION PRI","personal":"INGENIERO EN CIENCIAS AGRARIAS (LIDER DE ETE) Y AMBIENTAL 9","orden":9,"provincia":"Contumaza","utm1":"Contumaza, Matibamba","utm2":"Contumaza, Matibamba","utm3":"Contumaza, Matibamba","seccion":"Sección 9","area":"Área 1-5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P78-CAJ-PRI-CAMP-ING-EN-CS-AGR-LDR-DE-ETE-Y-AMB","objeto":"materia técnica para coordinar, monitorear y efectuar el seguimiento al equipo técnico especializado en actividades de campo de Predios Rurales Individuales – PRI"},
{"departamento":"Cajamarca","Nro":141,"PROCEDIMIENTO":"PERSONAL GANINETE PRI","personal":"INGENIERO RESPONSABLE DE SECTOR 1","orden":1,"provincia":"Cajamarca,Celendin,San Miguel,Contumaza,San Marcos,Cutervo,Chota","utm1":"","utm2":"","utm3":"","seccion":"","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P96-CAJ-PRI-GAB-ING-RSP-DE-SECT","objeto":"en materia técnica para coordinar, monitorear y efectuar el seguimiento del procedimiento de formalización y titulación de PRI y CC.CC"},
{"departamento":"Cajamarca","Nro":76,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 1","orden":1,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 1","area":"Área 1","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":77,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 10","orden":10,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 2","area":"Área 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":78,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 11","orden":11,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 3","area":"Área 1","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":79,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 12","orden":12,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 3","area":"Área 2","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":80,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 13","orden":13,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 3","area":"Área 3","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":81,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 14","orden":14,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 3","area":"Área 4","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":82,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 15","orden":15,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 3","area":"Área 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":83,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 16","orden":16,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 4","area":"Área 1","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":84,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 17","orden":17,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 4","area":"Área 2","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":85,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 18","orden":18,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 4","area":"Área 3","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":86,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 19","orden":19,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 4","area":"Área 4","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":87,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 2","orden":2,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 1","area":"Área 2","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":88,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 20","orden":20,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 4","area":"Área 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":89,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 21","orden":21,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 5","area":"Área 1","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":90,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 22","orden":22,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 5","area":"Área 2","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":91,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 23","orden":23,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 5","area":"Área 3","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":92,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 24","orden":24,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 5","area":"Área 4","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":93,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 25","orden":25,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 5","area":"Área 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":94,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 26","orden":26,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 6","area":"Área 1","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":95,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 27","orden":27,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 6","area":"Área 2","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":96,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 28","orden":28,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 6","area":"Área 3","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":97,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 29","orden":29,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 6","area":"Área 4","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":98,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 3","orden":3,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 1","area":"Área 3","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":99,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 30","orden":30,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 6","area":"Área 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":100,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 31","orden":31,"provincia":"San Miguel","utm1":"Catilluc","utm2":"Cochan ","utm3":"Llapa","seccion":"Sección 7","area":"Área 1","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":101,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 32","orden":32,"provincia":"San Miguel","utm1":"Catilluc","utm2":"Cochan ","utm3":"Llapa","seccion":"Sección 7","area":"Área 2","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":102,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 33","orden":33,"provincia":"San Miguel","utm1":"Catilluc","utm2":"Cochan ","utm3":"Llapa","seccion":"Sección 7","area":"Área 3","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":103,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 34","orden":34,"provincia":"San Miguel","utm1":"Catilluc","utm2":"Cochan ","utm3":"Llapa","seccion":"Sección 7","area":"Área 4","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":104,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 35","orden":35,"provincia":"San Miguel","utm1":"Catilluc","utm2":"Cochan ","utm3":"Llapa","seccion":"Sección 7","area":"Área 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":105,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 36","orden":36,"provincia":"San Miguel","utm1":"Catilluc","utm2":"Cochan","utm3":"Llapa","seccion":"Sección 8","area":"Área 1","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":106,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 37","orden":37,"provincia":"San Miguel","utm1":"Catilluc","utm2":"Cochan","utm3":"Llapa","seccion":"Sección 8","area":"Área 2","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":107,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 38","orden":38,"provincia":"San Miguel","utm1":"Catilluc","utm2":"Cochan","utm3":"Llapa","seccion":"Sección 8","area":"Área 3","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":108,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 39","orden":39,"provincia":"San Miguel","utm1":"Catilluc","utm2":"Cochan","utm3":"Llapa","seccion":"Sección 8","area":"Área 4","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":109,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 4","orden":4,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 1","area":"Área 4","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":110,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 40","orden":40,"provincia":"San Miguel","utm1":"Catilluc","utm2":"Cochan","utm3":"Llapa","seccion":"Sección 8","area":"Área 5","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":111,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 41","orden":41,"provincia":"Contumaza","utm1":"Contumaza","utm2":"Contumaza","utm3":"Contumaza","seccion":"Sección 9","area":"Área 1","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":112,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 42","orden":42,"provincia":"Contumaza","utm1":"Contumaza, Matibamba","utm2":"Contumaza, Matibamba","utm3":"Contumaza, Matibamba","seccion":"Sección 9","area":"Área 2","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":113,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 43","orden":43,"provincia":"Contumaza","utm1":"Contumaza, Matibamba","utm2":"Contumaza, Matibamba","utm3":"Contumaza, Matibamba","seccion":"Sección 9","area":"Área 3","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":126,"PROCEDIMIENTO":"PERSONAL CAMPO PRI","personal":"TECNICO EN ENFERMERIA 1","orden":1,"provincia":"Celendin, Contumaza","utm1":"Pallan, Contumaza","utm2":"Pallan, Contumaza","utm3":"Pallan, Contumaza","seccion":"Sección 1 al 10","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P75-CAJ-PRI-CAMP-TEC-EN-ENF","objeto":"en materia de salud, en la aplicación del protocolo para la implementación de medidas de vigilancia, prevención y control frente al Covid-19 en la actividad de titulación  de la propiedad agraria y  de catastro rural"},
{"departamento":"Cajamarca","Nro":127,"PROCEDIMIENTO":"PERSONAL CAMPO PRI","personal":"TECNICO EN ENFERMERIA 2","orden":2,"provincia":"San Miguel, Celendin","utm1":"Llapa, Chalan","utm2":"Llapa, Chalan","utm3":"Llapa, Chalan","seccion":"Sección 1 al 10","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P75-CAJ-PRI-CAMP-TEC-EN-ENF","objeto":"en materia de salud, en la aplicación del protocolo para la implementación de medidas de vigilancia, prevención y control frente al Covid-19 en la actividad de titulación  de la propiedad agraria y  de catastro rural"},
{"departamento":"Cajamarca","Nro":128,"PROCEDIMIENTO":"PERSONAL CAMPO PRI","personal":"TECNICO EN ENFERMERIA 3","orden":3,"provincia":"San Miguel, Celendin","utm1":"Catilluc, Cortegana","utm2":"Catilluc, Cortegana","utm3":"Catilluc, Cortegana","seccion":"Sección 1 al 10","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P75-CAJ-PRI-CAMP-TEC-EN-ENF","objeto":"en materia de salud, en la aplicación del protocolo para la implementación de medidas de vigilancia, prevención y control frente al Covid-19 en la actividad de titulación  de la propiedad agraria y  de catastro rural"},
{"departamento":"Cajamarca","Nro":129,"PROCEDIMIENTO":"PERSONAL CAMPO PRI","personal":"TECNICO EN ENFERMERIA 4","orden":4,"provincia":"San Miguel, Celendin y Contumaza","utm1":"Cochan, Chalan, Contumaza","utm2":"Cochan, Chalan, Contumaza","utm3":"Cochan, Chalan, Contumaza","seccion":"Sección 1 al 10","area":"","GRUPO":"PERSONAL CAMPO","tipopredio":"PRI","codigopersonal":"P75-CAJ-PRI-CAMP-TEC-EN-ENF","objeto":"en materia de salud, en la aplicación del protocolo para la implementación de medidas de vigilancia, prevención y control frente al Covid-19 en la actividad de titulación  de la propiedad agraria y  de catastro rural"},
{"departamento":"Cajamarca","Nro":114,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 44","orden":44,"provincia":"Contumaza","utm1":"Contumaza, Matibamba","utm2":"Contumaza, Matibamba","utm3":"Contumaza, Matibamba","seccion":"Sección 9","area":"Área 4","GRUPO":"PERSONAL GABINETE","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":115,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 45","orden":45,"provincia":"Contumaza","utm1":"Contumaza, Matibamba","utm2":"Contumaza, Matibamba","utm3":"Contumaza, Matibamba","seccion":"Sección 9","area":"Área 5","GRUPO":"PERSONAL GABINETE","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":116,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 46","orden":46,"provincia":"Contumaza","utm1":"Contumaza, Matibamba","utm2":"Contumaza, Matibamba","utm3":"Contumaza, Matibamba","seccion":"Sección 10","area":"Área 1","GRUPO":"PERSONAL GABINETE","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":117,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 47","orden":47,"provincia":"Contumaza","utm1":"Contumaza, Matibamba","utm2":"Contumaza, Matibamba","utm3":"Contumaza, Matibamba","seccion":"Sección 10","area":"Área 2","GRUPO":"PERSONAL GABINETE","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":118,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 48","orden":48,"provincia":"Contumaza","utm1":"Contumaza, Matibamba","utm2":"Contumaza, Matibamba","utm3":"Contumaza, Matibamba","seccion":"Sección 10","area":"Área 3","GRUPO":"PERSONAL GABINETE","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":119,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 49","orden":49,"provincia":"Contumaza","utm1":"Contumaza, Matibamba","utm2":"Contumaza, Matibamba","utm3":"Contumaza, Matibamba","seccion":"Sección 10","area":"Área 4","GRUPO":"PERSONAL GABINETE","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":120,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 5","orden":5,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 1","area":"Área 5","GRUPO":"PERSONAL GABINETE","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":121,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 50","orden":50,"provincia":"Contumaza","utm1":"Contumaza, Matibamba","utm2":"Contumaza, Matibamba","utm3":"Contumaza, Matibamba","seccion":"Sección 10","area":"Área 5","GRUPO":"PERSONAL GABINETE","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":122,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 6","orden":6,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 2","area":"Área 1","GRUPO":"PERSONAL GABINETE","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":123,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 7","orden":7,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 2","area":"Área 2","GRUPO":"PERSONAL GABINETE","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":124,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 8","orden":8,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 2","area":"Área 3","GRUPO":"PERSONAL GABINETE","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"},
{"departamento":"Cajamarca","Nro":125,"PROCEDIMIENTO":"TITULACION PRI","personal":"TECNICO DE CAMPO 9","orden":9,"provincia":"Celendin","utm1":"Pallan","utm2":"Cortegana","utm3":"Chumuch,Chalan","seccion":"Sección 2","area":"Área 4","GRUPO":"PERSONAL GABINETE","tipopredio":"PRI","codigopersonal":"P79-CAJ-PRI-CAMP-TEC-DE-CAMPO","objeto":"en materia técnica para el empadronamiento y levantamiento catastral de Predios Rurales Individuales - PRI"}]


def replace_parrafo(filename, textSearchParaffo,text_parrafo,destino):
    doc = Document(filename)
    style = doc.styles['Normal']
    font = style.font
    font.size = Pt(10)
    font.name = 'Arial'
    for p in doc.paragraphs:
        if textSearchParaffo in p.text:
            inline = p.runs
            # print(inline)
            # Loop added to work with runs (strings with same style)
            '''for i in range(len(inline)):
                if 'old text' in inline[i].text:
                    text = inline[i].text.replace('old text', 'new text')
                    inline[i].text = text
            '''
            #p.encode('utf-8')
            p.text = text_parrafo.decode('utf-8');
            p.style = doc.styles['Normal']
            #p.alignment = 1
    doc.save(destino)
    return 1

rutaTdrs="D:\\GTS\TDRS\\abril\\Cajamarca\\procesados\\"
rutaTdrscambiados="D:\\GTS\TDRS\\abril\\Cajamarca\\modificados\\"
print (len(datos))
for index, row in enumerate(datos, start=1):
    print(row["codigopersonal"])
    ut_cc_cn=""
    nom_ut_cc_cn = ""
    compuesto_ut=""
    seccion=""
    area=""
    if row["tipopredio"]=="CC.NN":
        ut_cc_cn="Comunidad(es) nativas"
    if row["tipopredio"] == "PRI":
        ut_cc_cn = "Unidades territoriales"
    if row["tipopredio"] == "CC.CC":
        ut_cc_cn = "Comunidad(es) campesinas"


    print("UT: " + ut_cc_cn)

    if row["utm1"]==row["utm2"] and row["utm2"]==row["utm3"]:
        nom_ut_cc_cn=row["utm2"]
    else:
        nom_ut_cc_cn = row["utm1"]+', '+row["utm2"]+', '+row["utm3"]

    if nom_ut_cc_cn.strip() != "":
        compuesto_ut = "" + ut_cc_cn+' de '+nom_ut_cc_cn

    print("Nombre UT: "+nom_ut_cc_cn)

    if row["seccion"].strip() != "":
        seccion = ", "+row["seccion"].strip()
        print("Seccion: "+ seccion)

    if row["area"].strip() != "":
        area = ", "+row["area"].strip()
        print("Area: " + area)

    objeto_contrata='Contratar un (1) servicio {} en el departamento {}, en la provincia(s) {}, {}{}{} en el marco de la ejecución del Proyecto "Catastro, Titulación y Registro de Tierras Rurales en el Perú, Tercera Etapa" - PTRT3-GTS.'.format(row["objeto"].strip(),row["departamento"].strip(),row["provincia"].strip(),compuesto_ut,seccion,area)

    #objeto
    print(objeto_contrata)

    #ejecuta el cambio
    rutatemplate=rutaTdrs+row["codigopersonal"]+'.docx'
    print(rutatemplate)
    destinoarchivo=rutaTdrscambiados+row["codigopersonal"]+'-'+str(row["orden"])+'.docx'
    print(destinoarchivo)

    replace_parrafo(rutatemplate,'Contratar ',objeto_contrata,destinoarchivo)
#text_parrafo='Contratación del '
#replace_parrafo("D:\\GTS\\TDRS\\HUANUCO\\GABINETE\\P145-HUA-PRI-GAB-ABG-CALIF.docx",'Contratar el servicio',text_parrafo,'destino6.docx')
